Deploy trickery

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -18,10 +18,11 @@ post_to_slack() {
   fi
 }
 
+origin="https://github.com/justarrived/justarrived.github.io/"
 main_branch=siteleaf
 release_branch=live
 
-__git-current-branch-or-exit $main_branch
+# __git-current-branch-or-exit $main_branch
 
 __exe_cmd "bundle exec jekyll build --config=_config.yml"
 if [ ! -d '_site' ]; then
@@ -29,21 +30,25 @@ if [ ! -d '_site' ]; then
   exit 1
 fi
 
-__exe_cmd "git fetch origin $release_branch"
-__exe_cmd "git checkout $release_branch"
+
+REMOTE_REPOSITORY=${REMOTE_REPOSITORY:?'You need to configure the REMOTE_REPOSITORY environment variable!'}
+REMOTE_BRANCH=${REMOTE_BRANCH:?'You need to configure the REMOTE_BRANCH environment variable!'}
+
+__exe_cmd "git fetch --unshallow || true"
+# __exe_cmd "git checkout $release_branch"
 error_code=$?
-if [ $error_code != 0 ]; then
-  echo 'Switch branch fail.'
-  exit
-else
+# if [ $error_code != 0 ]; then
+#   echo 'Switch branch fail.'
+#   exit
+# else
   ls | grep -v _site | grep -v CNAME | xargs rm -rf
   __exe_cmd "cp -r _site/* ."
   __exe_cmd "rm -rf _site/"
   __exe_cmd "touch .nojekyll"
   __exe_cmd "git add --all :/"
   __exe_cmd "git commit -m 'compile'"
-  __exe_cmd "git push -f origin $release_branch"
-  post_to_slack
-  __exe_cmd "git checkout $main_branch"
-fi
+  __exe_cmd "git push -f "${REMOTE_REPOSITORY}" "${CI_COMMIT_ID}:${REMOTE_BRANCH}""
+  # post_to_slack
+  # __exe_cmd "git checkout $main_branch"
+# fi
 echo 'deployed: https://justarrived.se'
