Reset script/deploy

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -6,31 +6,43 @@ cd "$(dirname "$0")/.."
 
 source script/_common
 
-# rvm use 2.4.1 --install
-# script/bootstrap
+post_to_slack() {
+  local slack_webhook_url=${JUST_ARRIVED_SE_SLACK_DEPLOY_HOOK_URL:-}
+  if [[ -z $slack_webhook_url ]]; then
+    echo '[WARNING] JUST_ARRIVED_SE_SLACK_DEPLOY_HOOK_URL not set! Please set in order to post to Slack on deploy.'
+  else
+    local data='{"text": "A new version of <https://justarrived.se|justarrived.se> has been deployed.", "channel": "#website", "username": "just-bot", "icon_emoji": ":shipit:"}'
 
-__exe_cmd "bundle exec jekyll build --config=_config.yml --trace"
+    echo 'Posting deploy to Slack..'
+    curl -X POST -H 'Content-type: application/json' --data $data $slack_webhook_url > /dev/null 2>&1 &
+  fi
+}
+
+main_branch=siteleaf
+release_branch=releasesiteleaf
+
+__git-current-branch-or-exit $main_branch
+
+__exe_cmd "bundle exec jekyll build --config=_config.yml"
 if [ ! -d '_site' ]; then
   echo "Jekyll build failed. Missing _site directory (no content to publish)"
   exit 1
 fi
 
-REMOTE_REPOSITORY=${REMOTE_REPOSITORY:?'You need to configure the REMOTE_REPOSITORY environment variable!'}
-REMOTE_BRANCH=${REMOTE_BRANCH:?'You need to configure the REMOTE_BRANCH environment variable!'}
-
-git config --global user.email "$GIT_USER_EMAIL"
-git config --global user.name "$GIT_USER_NAME"
-
-__exe_cmd "git fetch --unshallow || true" # see https://documentation.codeship.com/general/projects/push-to-remote-repositories/
-__exe_cmd "git fetch \"${REMOTE_REPOSITORY}\" \"+refs/heads/*:refs/remotes/origin/*\"" # see https://documentation.codeship.com/general/projects/push-to-remote-repositories/
-__exe_cmd "git checkout origin/release"
-__exe_cmd "ls | grep -v _site | grep -v CNAME | xargs rm -rf" # Remove all files except _site and CNAME
-__exe_cmd "cp -r _site/* ."
-__exe_cmd "rm -rf _site/"
-__exe_cmd "touch .nojekyll"
-__exe_cmd "git add --all :/"
-__exe_cmd "git commit --verbose --message 'compile'"
-__exe_cmd "git push -f "${REMOTE_REPOSITORY}" "$(git rev-parse HEAD):${REMOTE_BRANCH}"" # force push the latest commit
-
-echo "Deployed commit: ${CI_COMMIT_ID}"
+__exe_cmd "git checkout $release_branch"
+error_code=$?
+if [ $error_code != 0 ]; then
+  echo 'Switch branch fail.'
+  exit
+else
+  ls | grep -v _site | grep -v CNAME | xargs rm -rf
+  __exe_cmd "cp -r _site/* ."
+  __exe_cmd "rm -rf _site/"
+  __exe_cmd "touch .nojekyll"
+  __exe_cmd "git add --all :/"
+  __exe_cmd "git commit --message 'compile'"
+  __exe_cmd "git push -f origin $release_branch"
+  post_to_slack
+  __exe_cmd "git checkout $main_branch"
+fi
 echo 'deployed: https://justarrived.se'
